CREATE TABLE IF NOT EXISTS machine_performance_metrics (
  id SERIAL PRIMARY KEY,
  machine_id INTEGER REFERENCES machines(id),
  location_id INTEGER REFERENCES locations(id),
  date TIMESTAMP NOT NULL,
  uptime_minutes NUMERIC,
  downtime_minutes NUMERIC,
  availability_percentage NUMERIC,
  cycles_completed INTEGER,
  total_loads_processed INTEGER,
  average_cycle_time NUMERIC,
  error_count INTEGER,
  failure_rate NUMERIC,
  mtbf NUMERIC,
  energy_consumption NUMERIC,
  energy_efficiency NUMERIC,
  maintenance_count INTEGER,
  planned_maintenance_count INTEGER,
  unplanned_maintenance_count INTEGER,
  oee_score NUMERIC,
  performance_efficiency NUMERIC,
  quality_rate NUMERIC,
  utilization_rate NUMERIC,
  peak_utilization_time TEXT,
  cost_per_cycle NUMERIC,
  revenue_generated NUMERIC,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  last_updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);